# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "agent"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: agent
        image: liontao/rtree:0.1  # EDIT HERE: Replace the image nmae with [docker registry]/demo_actor:latest
        args: ["hypercorn", "agent.main:app","--bind","0.0.0.0:3000"]
        ports:
        - containerPort: 3000
        imagePullPolicy: Never