# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
  labels:
    app: index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "index"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: index
        image: liontao/rtree:0.1  # EDIT HERE: Replace the image nmae with [docker registry]/demo_actor:latest
        args: ["hypercorn", "idnex.main:app","--bind","0.0.0.0:3000"]
        ports:
        - containerPort: 3000
        imagePullPolicy: Never