# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
  labels:
    app: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress
  template:
    metadata:
      labels:
        app: ingress
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ingress"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: ingress
        image: liontao/rtree:0.1  # EDIT HERE: Replace the image nmae with [docker registry]/demo_actor:latest
        args: ["python", "ingress/main.py"]
        ports:
        - containerPort: 3000
        imagePullPolicy: Never